---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "devopsidiot-deployment.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "devopsidiot-deployment.fullname" . }}
  minReplicas: {{ .Values.minReplicaCount | default 1 }}
  maxReplicas: {{ .Values.maxReplicaCount | default 1 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60