{{- if .Values.minAvailable }}
{{- if or (.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget") (semverCompare ">=1.21" .Capabilities.KubeVersion.Version) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ template "devopsidiot-deployment.name" . }}-pdb"
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: "{{ template "devopsidiot-deployment.name" . }}"
{{- end }}
