name: Promote Release Candidate

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      RELEASE_WORKFLOW_TOKEN:
        required: true
      AWS_CREDENTIALS_FILE:
        required: true
      ID_RSA:
        required: true  

jobs:
  promote-RC-tag:
    runs-on: [ubuntu-latest]
    steps:
      - name: Git checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
          token: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
          fetch-depth: 0

      - name: AWS Credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "${{secrets.AWS_CREDENTIALS_FILE}}" > ~/.aws/credentials
          
      - name: Setup SSH Keys and known_hosts
        #  Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "${{secrets.ID_RSA}}" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"
          
      - name: promote release
        id: promotion
        env:
          GIT_AUTHOR_NAME: omaze-cicd
          GIT_AUTHOR_EMAIL: info@omaze.com
          GIT_COMMITTER_NAME: omaze-cicd
          GIT_COMMITTER_EMAIL: info@omaze.com
        run: |
          git merge refs/tags/${{ inputs.tag }}
          git push
          
      - name: promote docker image
        id: docker-forward
        env: 
          ENV: prd
          PREV_ENV: stg
          VERSION: ${{ inputs.tag }}
          PROMOTION_TAG: stg-promote-prd
          ACCOUNT_ID: 215691521637
          PREV_ACCOUNT_ID: 909409879842
        run: |
          make promote
