name: Semantic Pull Request Check

on:
  workflow_call:
    secrets:
      RELEASE_WORKFLOW_TOKEN:
        required: true
        
jobs:
  semantic-pr-check:
    name: Semantic Pull Request Check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
        with:
          types: |
            fix
            feat
            improvement
            docs
            refactor
            test
            ci
            chore
            
