name: Run Semantic-Release

on:
  workflow_call:
    secrets:
      RELEASE_WORKFLOW_TOKEN:
        required: true

jobs:
  release:
    name: 'Release to GitHub'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.RELEASE_WORKFLOW_TOKEN }}" > ~/.npmrc

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
          GIT_AUTHOR_NAME: omaze-cicd
          GIT_AUTHOR_EMAIL: info@omaze.com
          GIT_COMMITTER_NAME: omaze-cicd
          GIT_COMMITTER_EMAIL: info@omaze.com
        working-directory: ./.github/workflows
        run: |
          npm install --no-save \
            conventional-changelog-conventionalcommits
          npx semantic-release
