name: Integration Release Workflow

on:
  push:
    branches:
      - integration
    tags-ignore:
      - "*"
    paths-ignore:
      - ".github/**"
      - ".githooks/**"
      - "**.md"

jobs:
  release:
    name: "Release to GitHub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}
          GIT_AUTHOR_NAME: omaze-cicd
          GIT_AUTHOR_EMAIL: info@omaze.com
          GIT_COMMITTER_NAME: omaze-cicd
          GIT_COMMITTER_EMAIL: info@omaze.com
        run: |
          npm install --no-save \
            conventional-changelog-conventionalcommits \
            @semantic-release/git
          npx semantic-release
